### ISSUE TITLE
TODO: Make documentation on how to contribute

### ISSUE THREAD

**Issue by ImAciidz** [l4dsr/l4dsr-wiki#1]
- [X] Cover creating embeds, using admonitions, etc.
- [X] Give detailed-ish instructions on how to set up the dev environment
- [ ] Actually complete the instructions completely

**Comment by ImAciidz** [comment]
Finished task 1 in https://github.com/l4dsr/l4dsr-wiki/commit/fe3a2f2199f2a14e04c3da1c090d6c9560c5ced3, however I'd like to expand on this and give some basic instructions on how to set up the dev environment (probably just going to rip straight from the Titanfall 2 wiki to some extent lol)

**Comment by ImAciidz** [comment]
Mostly finished task 2 in https://github.com/l4dsr/l4dsr-wiki/commit/95fe4103e0cf24649f7581b9cdf7027fb660b09e, still can be improved, still some TODOs and missing details, but it's enough for newbies to work on it.

Added task 3 as it's still not completely complete (yet).
